"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LIST_REQUEST = "LIST_REQUEST";
exports.LIST_UPDATE = "LIST_UPDATE";
exports.LIST_SUCCESS = "LIST_SUCCESS";
exports.LIST_FAILURE = "LIST_FAILURE";
exports.DETAIL_REQUEST = "DETAIL_REQUEST";
exports.DETAIL_UPDATE = "DETAIL_UPDATE";
exports.DETAIL_SUCCESS = "DETAIL_SUCCESS";
exports.DETAIL_FAILURE = "DETAIL_FAILURE";
exports.UPLOAD_REQUEST = "UPLOAD_REQUEST";
exports.UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
exports.UPLOAD_FAILURE = "UPLOAD_FAILURE";
//   
